package com.example.calldelegate.testing.wav

import com.example.calldelegate.core.audio.capture.StreamingTurnAudioInputSource
import com.example.calldelegate.core.audio.capture.WavInjectionMode
import com.example.calldelegate.domain.model.SecondaryRecognitionExperimentMode
import com.example.calldelegate.domain.model.RuleDebugTrace
import kotlinx.serialization.Serializable
import java.io.File

const val WAV_CALL_MANIFEST_SCHEMA_VERSION = 3
const val WAV_CALL_MANIFEST_LEGACY_SCHEMA_VERSION = 2
const val WAV_CALL_RESULT_SCHEMA_VERSION = 19
const val CER_NORMALIZATION_VERSION = "cer-v1"
const val ENTITY_NORMALIZATION_VERSION = "entity-v1"

@Serializable
enum class WavCallMeasurementMode(
    val inspectsRemainingFrames: Boolean,
) {
    SEGMENTATION_AUDIT(true),
    PRODUCTION_LATENCY(false),
}

data class WavCallTestRequest(
    val manifestFile: File,
    val injectionMode: WavInjectionMode,
    val measurementMode: WavCallMeasurementMode = WavCallMeasurementMode.SEGMENTATION_AUDIT,
    val tailSilenceMs: Long = 800L,
    val disableMaxTurnDuration: Boolean = false,
    val outputRoot: File? = null,
    val gitCommit: String? = null,
    val baselineReference: String? = null,
    val secondaryRecognitionMode: SecondaryRecognitionExperimentMode =
        SecondaryRecognitionExperimentMode.DISABLED,
    val voskChunkDurationMs: Long = StreamingTurnAudioInputSource.DEFAULT_RECOGNITION_CHUNK_DURATION_MS,
    val endpointGraceMs: Long = StreamingTurnAudioInputSource.DEFAULT_ENDPOINT_GRACE_MS,
    /**
     * Short grace applied only on completeness evidence. Defaults to [endpointGraceMs], which
     * disables the early path, so an unset batch measures exactly today's production behavior.
     */
    val earlyEndpointGraceMs: Long = endpointGraceMs,
    val nominalRamOverrideGb: Int? = null,
    val maxAlternativesOverride: Int? = null,
)

data class WavCallRunReport(
    val runId: String,
    val resultDirectory: File,
    val summary: WavCallRunSummary,
    val samples: List<WavCallSampleResult>,
)

@Serializable
data class WavCallRunSummary(
    val schemaVersion: Int = WAV_CALL_RESULT_SCHEMA_VERSION,
    val runId: String,
    val status: WavCallRunStatus,
    val startedAtElapsedRealtimeNanos: Long,
    val completedAtElapsedRealtimeNanos: Long,
    val manifestVersion: String?,
    val injectionMode: String,
    val measurementMode: String = WavCallMeasurementMode.SEGMENTATION_AUDIT.name,
    val acceleratedInput: Boolean,
    val environment: WavCallRunEnvironment,
    val modeSummaries: List<WavCallModeSummary>,
    val completedCaseCount: Int,
    val failureCaseCount: Int,
    val cancellationRequested: Boolean,
    val batchFailureCode: String? = null,
    val batchFailureMessage: String? = null,
)

@Serializable
enum class WavCallRunStatus {
    COMPLETED,
    CANCELLED,
    BATCH_FAILED,
}

@Serializable
data class WavCallRunEnvironment(
    val applicationVersion: String?,
    val buildType: String?,
    val gitCommit: String?,
    val baselineReference: String?,
    val deviceModel: String?,
    val androidVersion: String?,
    val soc: String?,
    val supportedAbis: List<String>,
    val totalRamBytes: Long?,
    val asrModelName: String?,
    val asrModelVersion: String?,
    val asrModelPath: String?,
    val asrRuntime: String?,
    val ttsModelName: String?,
    val ttsModelVersion: String?,
    val ttsModelPath: String?,
    val ttsRuntime: String?,
    val ttsVoice: String?,
    val ttsLocale: String?,
    val inferenceThreadCount: Int?,
    val wavTurnDurationLimitMillis: Long?,
    val wavTurnDurationLimitDisabled: Boolean,
    val vadImplementation: String?,
    val vadRmsThreshold: Double?,
    val vadEndSilenceFrames: Int?,
    val vadInitialSilenceFrames: Int?,
    val vadFrameSamples: Int,
    val tailSilenceMs: Long,
    val cerNormalizationVersion: String = CER_NORMALIZATION_VERSION,
    val entityNormalizationVersion: String = ENTITY_NORMALIZATION_VERSION,
    val queueCapacity: Int? = null,
    val queueOverflowPolicy: String? = null,
    val queueMetricReason: String? = null,
    val vadEndSilenceMs: Long? = null,
    val vadInitialSilenceMs: Long? = null,
    val vadSubframeDurationMs: Long? = null,
    val endpointGraceMs: Long? = null,
    val earlyEndpointGraceMs: Long? = null,
    val maxCandidateRollbackCount: Int? = null,
    val secondaryRecognitionMode: String = SecondaryRecognitionExperimentMode.DISABLED.name,
    val voskChunkDurationMs: Long = 20L,
    val nominalRamOverrideGb: Int? = null,
    val effectiveDeviceTier: String? = null,
    val baseDeviceTier: String? = null,
    val devicePolicy: String? = null,
    val deviceProfileReasons: List<String> = emptyList(),
    val maxAlternativesOverride: Int? = null,
)

@Serializable
data class WavCallModeSummary(
    val injectionMode: String,
    val measurementMode: String = WavCallMeasurementMode.SEGMENTATION_AUDIT.name,
    val acceleratedInput: Boolean,
    val totalCases: Int,
    val passedCases: Int,
    val failedCases: Int,
    val noSpeechCases: Int,
    val multipleUtteranceCases: Int,
    val cancelledCases: Int,
    val globalCer: Double?,
    val cerTotalEditDistance: Long,
    val cerTotalReferenceLength: Long,
    val globalSourceRtf: Double?,
    val globalAsrRtf: Double?,
    val voskComputeDurationMs: Long,
    val originalAudioDurationMs: Long,
    val voskInputAudioDurationMs: Long,
    val sceneAccuracy: Double?,
    val sceneEvaluatedCases: Int,
    val sceneMatchedCases: Int,
    val sceneCandidateAccuracy: Double? = null,
    val sceneCandidateMatchedCases: Int = 0,
    val sceneConfirmedAccuracy: Double? = null,
    val sceneConfirmedMatchedCases: Int = 0,
    val sceneConfirmedCases: Int = 0,
    val firstTurnSceneEvaluatedCases: Int = 0,
    val firstTurnSceneMatchedCases: Int = 0,
    val firstTurnSceneAccuracy: Double? = null,
    val continuationSceneEvaluatedCases: Int = 0,
    val continuationSceneRetainedCases: Int = 0,
    val continuationSceneRetentionRate: Double? = null,
    val deliveryIntentEvaluatedCases: Int = 0,
    val deliveryIntentMatchedCases: Int = 0,
    val deliveryIntentAccuracy: Double? = null,
    val intentEvaluatedCases: Int = 0,
    val intentMatchedCases: Int = 0,
    val intentAccuracy: Double? = null,
    val callNatureEvaluatedCases: Int = 0,
    val callNatureMatchedCases: Int = 0,
    val callNatureAccuracy: Double? = null,
    val riskEvaluatedCases: Int = 0,
    val riskMatchedCases: Int = 0,
    val riskAccuracy: Double? = null,
    val entityTp: Long,
    val entityFp: Long,
    val entityFn: Long,
    val entityPrecision: Double?,
    val entityRecall: Double?,
    val entityF1: Double?,
    val strictEntityMatchedCases: Int = 0,
    val requiredEntityEvaluatedCases: Int = 0,
    val requiredEntityIncludedCases: Int = 0,
    val requiredEntityInclusionRate: Double? = null,
    val locationEvaluatedCases: Int = 0,
    val locationMatchedCases: Int = 0,
    val locationAccuracy: Double? = null,
    val locationExactMatchedCases: Int = 0,
    val locationExactAccuracy: Double? = null,
    val locationCoreIncludedCases: Int = 0,
    val locationCoreInclusionRate: Double? = null,
    val locationHierarchyMatchedCases: Int = 0,
    val locationHierarchyMatchRate: Double? = null,
    val hotwordExpectedCount: Long = 0,
    val hotwordMatchedCount: Long = 0,
    val hotwordAccuracy: Double? = null,
    val firstPassGlobalCer: Double? = null,
    val firstPassCerTotalEditDistance: Long = 0,
    val firstPassCerTotalReferenceLength: Long = 0,
    val secondaryRecognitionCases: Int = 0,
    val secondaryRecognitionRate: Double? = null,
    val secondaryRecognitionComputeDurationMs: Long = 0,
    val secondaryRecognitionAdoptedCases: Int = 0,
    val secondaryEvidenceUsedCases: Int = 0,
    val secondaryScenePromotedCases: Int = 0,
    val secondaryEntitySupplementedCases: Int = 0,
    val secondaryTextReplacementCases: Int = 0,
    val singlePassCases: Int = 0,
    val singlePassAsrLatencyP50Ms: Long? = null,
    val singlePassAsrLatencyP95Ms: Long? = null,
    val singlePassResponseLatencyP50Ms: Long? = null,
    val singlePassResponseLatencyP95Ms: Long? = null,
    val singlePassPeakPssKb: Int? = null,
    val secondaryPathAsrLatencyP50Ms: Long? = null,
    val secondaryPathAsrLatencyP95Ms: Long? = null,
    val secondaryPathIncrementLatencyP50Ms: Long? = null,
    val secondaryPathIncrementLatencyP95Ms: Long? = null,
    val secondaryPathResponseLatencyP50Ms: Long? = null,
    val secondaryPathResponseLatencyP95Ms: Long? = null,
    val secondaryPathPeakPssKb: Int? = null,
    val asrComputeDurationP50Ms: Long? = null,
    val asrComputeDurationP90Ms: Long? = null,
    val asrComputeDurationP95Ms: Long? = null,
    val vadFrameProcessingLagP50Ms: Long? = null,
    val vadFrameProcessingLagP95Ms: Long? = null,
    val vadFrameProcessingLagMaxMs: Long? = null,
    val recognizerCreateP50Ms: Long? = null,
    val recognizerCreateP95Ms: Long? = null,
    val voskAcceptComputeP50Ms: Long? = null,
    val voskAcceptComputeP95Ms: Long? = null,
    val voskQueueDepthMax: Int? = null,
    val voskQueueWaitP50Ms: Long? = null,
    val voskQueueWaitP95Ms: Long? = null,
    val voskDrainP50Ms: Long? = null,
    val voskDrainP95Ms: Long? = null,
    val voskFinalResultP50Ms: Long? = null,
    val voskFinalResultP95Ms: Long? = null,
    val referenceEndToAsrCompleteP50Ms: Long? = null,
    val referenceEndToAsrCompleteP90Ms: Long? = null,
    val referenceEndToAsrCompleteP95Ms: Long? = null,
    val asrPostEndpointLatencyP50Ms: Long? = null,
    val asrPostEndpointLatencyP90Ms: Long? = null,
    val asrPostEndpointLatencyP95Ms: Long? = null,
    val nluDurationP50Ms: Long? = null,
    val nluDurationP90Ms: Long? = null,
    val nluDurationP95Ms: Long? = null,
    val ttsSynthesisDurationP50Ms: Long? = null,
    val ttsSynthesisDurationP90Ms: Long? = null,
    val ttsSynthesisDurationP95Ms: Long? = null,
    val ttsToFirstAudioWriteLatencyP50Ms: Long? = null,
    val ttsToFirstAudioWriteLatencyP90Ms: Long? = null,
    val ttsToFirstAudioWriteLatencyP95Ms: Long? = null,
    val responseLatencyP50Ms: Long? = null,
    val responseLatencyP90Ms: Long? = null,
    val responseLatencyP95Ms: Long? = null,
    val validResponseLatencySampleCount: Int = 0,
    val responseLatencyMaxMs: Long? = null,
    val candidateEndpointRollbackCount: Int = 0,
    val speechResumedAfterCandidateP50Ms: Long? = null,
    val speechResumedAfterCandidateP90Ms: Long? = null,
    val speechResumedAfterCandidateP95Ms: Long? = null,
    val speechResumedAfterCandidateMaxMs: Long? = null,
    val partialFinalEvaluatedCases: Int = 0,
    val partialFinalExactMatchedCases: Int = 0,
    val partialFinalExactMatchRate: Double? = null,
    val partialFinalNormalizedMatchedCases: Int = 0,
    val partialFinalNormalizedMatchRate: Double? = null,
    val partialFinalCharacterDifference: Long = 0,
    val macroF1: Double? = null,
    val perSceneMetrics: List<WavSceneMetric> = emptyList(),
    val confusionMatrix: Map<String, Map<String, Int>> = emptyMap(),
)

@Serializable
data class WavSceneMetric(
    val scene: String,
    val truePositive: Int,
    val falsePositive: Int,
    val falseNegative: Int,
    val precision: Double?,
    val recall: Double?,
    val f1: Double?,
)

@Serializable
data class WavRecognitionAttempt(
    val attemptIndex: Int,
    val mode: String,
    val sceneHints: List<String>,
    val recognizedTextRaw: String?,
    val computeDurationMs: Long,
    val errorCode: String?,
    val adopted: Boolean,
    val recognitionFocuses: List<String> = emptyList(),
    val unknownTokenCount: Int = 0,
    val alternativeCount: Int? = null,
    val meanWordConfidence: Float? = null,
    val minimumWordConfidence: Float? = null,
    val recognizerCreateMs: Long? = null,
    val voskAcceptComputeMs: Long? = null,
    val voskQueueDepth: Int? = null,
    val voskQueueWaitMs: Long? = null,
    val voskQueueWaitMaxMs: Long? = null,
    val voskDrainMs: Long? = null,
    val voskFinalResultMs: Long? = null,
)

@Serializable
enum class WavCallCaseStatus {
    PASSED,
    FAILED,
    NO_SPEECH,
    MULTIPLE_UTTERANCES,
    CANCELLED,
}

@Serializable
data class WavCallSampleResult(
    val caseId: String,
    val wavFile: String,
    val injectionMode: String,
    val measurementMode: String = WavCallMeasurementMode.SEGMENTATION_AUDIT.name,
    val acceleratedInput: Boolean,
    val status: WavCallCaseStatus,
    val failureCode: String? = null,
    val failureMessage: String? = null,
    val originalAudioSamples: Long? = null,
    val originalAudioDurationMs: Long? = null,
    val tailSilenceMs: Long? = null,
    val injectedTailSamples: Long? = null,
    val framePaddingSamples: Long? = null,
    val framePaddingDurationMs: Long? = null,
    val emittedFrames: Long? = null,
    val endpointGroundTruthAvailable: Boolean = false,
    val speechStartInjectedAtElapsedRealtimeNanos: Long? = null,
    val speechEndInjectedAtElapsedRealtimeNanos: Long? = null,
    val speechEndReferenceAtElapsedRealtimeNanos: Long? = null,
    val responseLatencyReference: String? = null,
    val boundaryTimingResolutionMs: Long? = null,
    val vadSpeechStartMs: Long? = null,
    val vadSpeechEndMs: Long? = null,
    val vadLastSpeechMs: Long? = null,
    val speechEndToCommitAudioMs: Long? = null,
    val speechEndToCommitWallClockMs: Long? = null,
    val asrTrailingSilenceSkippedMs: Long? = null,
    val vadOutputAtElapsedRealtimeNanos: Long? = null,
    val vadStartOffsetMs: Long? = null,
    val vadEndOffsetMs: Long? = null,
    val vadPositiveEndpointDelayMs: Long? = null,
    val vadEarlyCutoffMs: Long? = null,
    val vadDecisionLatencyMs: Long? = null,
    val vadFrameProcessingLagMs: Long? = null,
    val endpointDetectionQuantizationMs: Long? = null,
    val candidateEndpointAtMs: List<Long> = emptyList(),
    val speechResumedAtMs: List<Long> = emptyList(),
    val speechResumedAfterCandidateMs: List<Long> = emptyList(),
    val candidateCancelledAtMs: List<Long> = emptyList(),
    val endpointCommittedAtMs: Long? = null,
    val candidateEndpointRollbackCount: Int = 0,
    val candidateRecognizerIds: List<String?> = emptyList(),
    val candidatePartialTextsRaw: List<String?> = emptyList(),
    val committedCandidateRecognizerId: String? = null,
    val committedCandidatePartialTextRaw: String? = null,
    val committedOnEarlyEndpointEvidence: Boolean = false,
    val committedEndpointGraceMs: Long? = null,
    val rollbackRecognizerStable: Boolean? = null,
    val partialFinalExactMatched: Boolean? = null,
    val partialFinalNormalizedMatched: Boolean? = null,
    val partialFinalCharacterDifference: Int? = null,
    val vadEndReason: String? = null,
    val voskComputeDurationMs: Long? = null,
    val voskInputAudioDurationMs: Long? = null,
    val asrStartedAtElapsedRealtimeNanos: Long? = null,
    val asrCompletedAtElapsedRealtimeNanos: Long? = null,
    val asrStageWallDurationMs: Long? = null,
    val asrPostEndpointLatencyMs: Long? = null,
    val referenceEndToAsrCompleteMs: Long? = null,
    val recognizerCreateMs: Long? = null,
    val voskAcceptComputeMs: Long? = null,
    val voskQueueDepth: Int? = null,
    val voskQueueWaitMs: Long? = null,
    val voskQueueWaitMaxMs: Long? = null,
    val voskDrainMs: Long? = null,
    val voskFinalResultMs: Long? = null,
    val nluStartedAtElapsedRealtimeNanos: Long? = null,
    val nluCompletedAtElapsedRealtimeNanos: Long? = null,
    val nluDurationMs: Long? = null,
    val asrToNluGapMs: Long? = null,
    val ttsStartedAtElapsedRealtimeNanos: Long? = null,
    val ttsCompletedAtElapsedRealtimeNanos: Long? = null,
    val ttsSynthesisDurationMs: Long? = null,
    val nluToTtsGapMs: Long? = null,
    val ttsToFirstAudioWriteLatencyMs: Long? = null,
    val endpointToTtsCompletedLatencyMs: Long? = null,
    val sourceRtf: Double? = null,
    val asrRtf: Double? = null,
    val recognizedTextRaw: String? = null,
    val recognizedTextNormalized: String? = null,
    val referenceTextRaw: String? = null,
    val referenceTextNormalized: String? = null,
    val cerEditDistance: Int? = null,
    val cerReferenceLength: Int? = null,
    val cer: Double? = null,
    val firstPassRecognizedTextRaw: String? = null,
    val firstPassRecognizedTextNormalized: String? = null,
    val firstPassCerEditDistance: Int? = null,
    val firstPassCerReferenceLength: Int? = null,
    val firstPassCer: Double? = null,
    val recognitionAttemptCount: Int = 0,
    val recognitionAttempts: List<WavRecognitionAttempt> = emptyList(),
    val selectedRecognitionAttemptIndex: Int? = null,
    val secondaryRecognitionTriggered: Boolean = false,
    val secondaryRecognitionComputeDurationMs: Long = 0,
    val selectedRecognitionMode: String? = null,
    val secondaryPassRecognizedTextRaw: String? = null,
    val secondaryPassCer: Double? = null,
    val secondaryTextDifferenceRate: Double? = null,
    val secondaryTriggerReasons: List<String> = emptyList(),
    val secondaryMatchedHotwordsByScene: Map<String, List<String>> = emptyMap(),
    val primaryNluScene: String? = null,
    val primaryNluConfidence: Float? = null,
    val primaryNluSceneMargin: Float? = null,
    val primaryNluEntities: Map<String, String> = emptyMap(),
    val secondaryNluScene: String? = null,
    val secondaryNluConfidence: Float? = null,
    val secondaryNluSceneMargin: Float? = null,
    val secondaryNluEntities: Map<String, String> = emptyMap(),
    val secondaryFusionReasons: List<String> = emptyList(),
    val secondaryEvidenceUsed: Boolean = false,
    val secondaryScenePromoted: Boolean = false,
    val secondaryAcceptedEntityKeys: List<String> = emptyList(),
    val secondaryTextReplaced: Boolean = false,
    /**
     * What the recognizer's N-best list offered this turn and what was done with it.
     *
     * [nBestAlternatives] is recorded whether or not a rerank happened, because a run that only
     * reported its substitutions could not tell a lattice that lacked the right reading from
     * acceptance rules that turned it down -- and those need opposite fixes.
     */
    val asrAlternativeCount: Int? = null,
    val asrMeanWordConfidence: Float? = null,
    val asrMinimumWordConfidence: Float? = null,
    val nBestAlternatives: List<String> = emptyList(),
    val rerankExaminedHypotheses: Int? = null,
    val rerankTriggered: Boolean = false,
    val rerankChosenRank: Int? = null,
    val rerankUnderstoodText: String? = null,
    val rerankReasons: List<String> = emptyList(),
    val generatedReply: String? = null,
    val replyTemplateId: String? = null,
    val replyVariables: Map<String, String> = emptyMap(),
    val isFallbackTemplate: Boolean? = null,
    val fallbackReason: String? = null,
    val replySafe: Boolean? = null,
    val replyCharCount: Int? = null,
    val replyAudioDurationMs: Long? = null,
    val complianceFlags: List<String> = emptyList(),
    val finalNluScene: String? = null,
    val finalNluIntent: String? = null,
    val topicScene: String? = null,
    val finalNluCallNature: String? = null,
    val finalNluRiskLevel: String? = null,
    val finalNluConfidence: Float? = null,
    val finalNluSceneMargin: Float? = null,
    val shouldClarify: Boolean? = null,
    val sceneCandidates: List<String> = emptyList(),
    val riskReasons: List<String> = emptyList(),
    val nluMatchedEvidence: List<String> = emptyList(),
    val nluRejectedEvidence: List<String> = emptyList(),
    val ruleDebugTrace: RuleDebugTrace? = null,
    val initialScene: String? = null,
    val expectedScene: String? = null,
    val actualScene: String? = null,
    val sceneConfidenceState: String? = null,
    val sceneMatched: Boolean? = null,
    val expectedIntent: String? = null,
    val intentMatched: Boolean? = null,
    val expectedCallNature: String? = null,
    val callNatureMatched: Boolean? = null,
    val expectedRiskLevel: String? = null,
    val riskLevelMatched: Boolean? = null,
    val expectedDigitSpans: List<List<Int>> = emptyList(),
    val expectedDeliveryIntent: String? = null,
    val actualDeliveryIntent: String? = null,
    val deliveryIntentMatched: Boolean? = null,
    val deliveryIntentScore: Float? = null,
    val deliveryIntentDecisionRule: String? = null,
    val deliveryIntentMatchedEvidence: List<String> = emptyList(),
    val deliveryIntentRejectedCandidates: List<String> = emptyList(),
    val expectedEntities: Map<String, String> = emptyMap(),
    val entityEvaluationEnabled: Boolean = true,
    val expectedHotwords: List<String> = emptyList(),
    val matchedHotwordCount: Int = 0,
    val hotwordAccuracy: Double? = null,
    val actualEntities: Map<String, String> = emptyMap(),
    val entityTp: Int? = null,
    val entityFp: Int? = null,
    val entityFn: Int? = null,
    val entityPrecision: Double? = null,
    val entityRecall: Double? = null,
    val entityF1: Double? = null,
    val strictEntitiesMatched: Boolean? = null,
    val requiredEntitiesIncluded: Boolean? = null,
    val locationMatched: Boolean? = null,
    val locationExactMatched: Boolean? = null,
    val locationCoreIncluded: Boolean? = null,
    val locationHierarchyMatched: Boolean? = null,
    val playbackRequestedAtElapsedRealtimeMs: Long? = null,
    val firstAudioWriteAtElapsedRealtimeMs: Long? = null,
    val playbackStartedAtElapsedRealtimeMs: Long? = null,
    val playbackCompletedAtElapsedRealtimeMs: Long? = null,
    val outputMode: String? = null,
    val playbackErrorCode: String? = null,
    val ttsFirstAudioWriteLatencyMs: Long? = null,
    val playbackStartLatencyMs: Long? = null,
    val playbackDurationMs: Long? = null,
    val responseLatencyMs: Long? = null,
    val turnTotalDurationMs: Long? = null,
    val peakProcessPssKb: Int? = null,
    val unavailableReasons: Map<String, String> = emptyMap(),
)
