package com.example.calldelegate.testing.wav

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID

@OptIn(ExperimentalSerializationApi::class)
class WavCallResultExporter {
    private val json = Json {
        prettyPrint = true
        encodeDefaults = true
        explicitNulls = true
    }

    fun createRunDirectory(root: File): Pair<String, File> {
        if (!root.exists() && !root.mkdirs()) {
            throw IllegalStateException("无法创建 WAV 测试结果根目录")
        }
        if (!root.isDirectory || !root.canWrite()) {
            throw IllegalStateException("WAV 测试结果根目录不可写")
        }
        val timestamp = SimpleDateFormat("yyyyMMdd-HHmmss-SSS", Locale.ROOT).format(Date())
        val runId = "wav-call-$timestamp-${UUID.randomUUID()}"
        val directory = File(root, runId)
        if (!directory.mkdir()) {
            throw IllegalStateException("无法创建唯一 WAV 测试结果目录")
        }
        return runId to directory
    }

    fun write(
        directory: File,
        summary: WavCallRunSummary,
        samples: List<WavCallSampleResult>,
    ) {
        if (!directory.isDirectory || !directory.canWrite()) {
            throw IllegalStateException("WAV 测试结果目录不可写")
        }
        File(directory, "summary.json").writeText(json.encodeToString(summary), Charsets.UTF_8)
        File(directory, "samples.json").writeText(json.encodeToString(samples), Charsets.UTF_8)
        File(directory, "samples.csv").writeText(samplesToCsv(samples), Charsets.UTF_8)
        val failures = samples.filter { it.status != WavCallCaseStatus.PASSED }
        File(directory, "failures.json").writeText(
            json.encodeToString(WavCallFailures(summary.runId, failures)),
            Charsets.UTF_8,
        )
    }

    private fun samplesToCsv(samples: List<WavCallSampleResult>): String {
        val rows = ArrayList<String>(samples.size + 1)
        rows += listOf(
            "caseId",
            "wavFile",
            "injectionMode",
            "measurementMode",
            "acceleratedInput",
            "status",
            "failureCode",
            "originalAudioDurationMs",
            "speechEndInjectedAtElapsedRealtimeNanos",
            "speechEndReferenceAtElapsedRealtimeNanos",
            "responseLatencyReference",
            "vadSpeechStartMs",
            "vadSpeechEndMs",
            "vadLastSpeechMs",
            "speechEndToCommitAudioMs",
            "speechEndToCommitWallClockMs",
            "asrTrailingSilenceSkippedMs",
            "endpointDetectionQuantizationMs",
            "candidateEndpointAtMs",
            "speechResumedAtMs",
            "speechResumedAfterCandidateMs",
            "candidateCancelledAtMs",
            "endpointCommittedAtMs",
            "candidateEndpointRollbackCount",
            "candidateRecognizerIds",
            "candidatePartialTextsRaw",
            "committedCandidateRecognizerId",
            "committedCandidatePartialTextRaw",
            "committedOnEarlyEndpointEvidence",
            "committedEndpointGraceMs",
            "rollbackRecognizerStable",
            "partialFinalExactMatched",
            "partialFinalNormalizedMatched",
            "partialFinalCharacterDifference",
            "vadFrameProcessingLagMs",
            "voskComputeDurationMs",
            "recognizerCreateMs",
            "voskAcceptComputeMs",
            "voskQueueDepth",
            "voskQueueWaitMs",
            "voskQueueWaitMaxMs",
            "voskDrainMs",
            "voskFinalResultMs",
            "asrStageWallDurationMs",
            "asrPostEndpointLatencyMs",
            "referenceEndToAsrCompleteMs",
            "nluDurationMs",
            "asrToNluGapMs",
            "ttsSynthesisDurationMs",
            "nluToTtsGapMs",
            "ttsToFirstAudioWriteLatencyMs",
            "endpointToTtsCompletedLatencyMs",
            "sourceRtf",
            "asrRtf",
            "recognizedTextRaw",
            "firstPassRecognizedTextRaw",
            "firstPassCer",
            "recognitionAttemptCount",
            "selectedRecognitionAttemptIndex",
            "secondaryRecognitionTriggered",
            "secondaryRecognitionComputeDurationMs",
            "selectedRecognitionMode",
            "secondaryPassRecognizedTextRaw",
            "secondaryPassCer",
            "secondaryTextDifferenceRate",
            "secondaryTriggerReasons",
            "secondaryMatchedHotwordsByScene",
            "primaryNluScene",
            "primaryNluConfidence",
            "secondaryNluScene",
            "secondaryNluConfidence",
            "secondaryFusionReasons",
            "secondaryEvidenceUsed",
            "secondaryScenePromoted",
            "secondaryAcceptedEntityKeys",
            "secondaryTextReplaced",
            "generatedReply",
            "replyTemplateId",
            "replyVariables",
            "isFallbackTemplate",
            "fallbackReason",
            "replySafe",
            "replyCharCount",
            "replyAudioDurationMs",
            "complianceFlags",
            "finalNluScene",
            "finalNluIntent",
            "topicScene",
            "finalNluCallNature",
            "finalNluRiskLevel",
            "finalNluConfidence",
            "finalNluSceneMargin",
            "shouldClarify",
            "sceneCandidates",
            "riskReasons",
            "nluMatchedEvidence",
            "nluRejectedEvidence",
            "ruleSceneScores",
            "ruleIntentScores",
            "ruleEvidence",
            "ruleFinalSceneSource",
            "riskMatchedIds",
            "riskRejectedIds",
            "riskContextExemptedIds",
            "recognizedTextNormalized",
            "referenceTextRaw",
            "referenceTextNormalized",
            "cerEditDistance",
            "cerReferenceLength",
            "cer",
            "initialScene",
            "expectedScene",
            "actualScene",
            "sceneConfidenceState",
            "sceneMatched",
            "expectedIntent",
            "intentMatched",
            "expectedCallNature",
            "callNatureMatched",
            "expectedRiskLevel",
            "riskLevelMatched",
            "expectedDigitSpans",
            "expectedDeliveryIntent",
            "actualDeliveryIntent",
            "deliveryIntentMatched",
            "deliveryIntentScore",
            "deliveryIntentDecisionRule",
            "deliveryIntentMatchedEvidence",
            "deliveryIntentRejectedCandidates",
            "entityTp",
            "entityFp",
            "entityFn",
            "entityPrecision",
            "entityRecall",
            "entityF1",
            "strictEntitiesMatched",
            "requiredEntitiesIncluded",
            "locationMatched",
            "locationExactMatched",
            "locationCoreIncluded",
            "locationHierarchyMatched",
            "hotwordAccuracy",
            "outputMode",
            "responseLatencyMs",
            "turnTotalDurationMs",
            "peakProcessPssKb",
        ).joinToString(",")
        for (sample in samples) {
            rows += listOf(
                sample.caseId,
                sample.wavFile,
                sample.injectionMode,
                sample.measurementMode,
                sample.acceleratedInput,
                sample.status.name,
                sample.failureCode,
                sample.originalAudioDurationMs,
                sample.speechEndInjectedAtElapsedRealtimeNanos,
                sample.speechEndReferenceAtElapsedRealtimeNanos,
                sample.responseLatencyReference,
                sample.vadSpeechStartMs,
                sample.vadSpeechEndMs,
                sample.vadLastSpeechMs,
                sample.speechEndToCommitAudioMs,
                sample.speechEndToCommitWallClockMs,
                sample.asrTrailingSilenceSkippedMs,
                sample.endpointDetectionQuantizationMs,
                sample.candidateEndpointAtMs,
                sample.speechResumedAtMs,
                sample.speechResumedAfterCandidateMs,
                sample.candidateCancelledAtMs,
                sample.endpointCommittedAtMs,
                sample.candidateEndpointRollbackCount,
                sample.candidateRecognizerIds,
                sample.candidatePartialTextsRaw,
                sample.committedCandidateRecognizerId,
                sample.committedCandidatePartialTextRaw,
                sample.committedOnEarlyEndpointEvidence,
                sample.committedEndpointGraceMs,
                sample.rollbackRecognizerStable,
                sample.partialFinalExactMatched,
                sample.partialFinalNormalizedMatched,
                sample.partialFinalCharacterDifference,
                sample.vadFrameProcessingLagMs,
                sample.voskComputeDurationMs,
                sample.recognizerCreateMs,
                sample.voskAcceptComputeMs,
                sample.voskQueueDepth,
                sample.voskQueueWaitMs,
                sample.voskQueueWaitMaxMs,
                sample.voskDrainMs,
                sample.voskFinalResultMs,
                sample.asrStageWallDurationMs,
                sample.asrPostEndpointLatencyMs,
                sample.referenceEndToAsrCompleteMs,
                sample.nluDurationMs,
                sample.asrToNluGapMs,
                sample.ttsSynthesisDurationMs,
                sample.nluToTtsGapMs,
                sample.ttsToFirstAudioWriteLatencyMs,
                sample.endpointToTtsCompletedLatencyMs,
                sample.sourceRtf,
                sample.asrRtf,
                sample.recognizedTextRaw,
                sample.firstPassRecognizedTextRaw,
                sample.firstPassCer,
                sample.recognitionAttemptCount,
                sample.selectedRecognitionAttemptIndex,
                sample.secondaryRecognitionTriggered,
                sample.secondaryRecognitionComputeDurationMs,
                sample.selectedRecognitionMode,
                sample.secondaryPassRecognizedTextRaw,
                sample.secondaryPassCer,
                sample.secondaryTextDifferenceRate,
                sample.secondaryTriggerReasons,
                sample.secondaryMatchedHotwordsByScene,
                sample.primaryNluScene,
                sample.primaryNluConfidence,
                sample.secondaryNluScene,
                sample.secondaryNluConfidence,
                sample.secondaryFusionReasons,
                sample.secondaryEvidenceUsed,
                sample.secondaryScenePromoted,
                sample.secondaryAcceptedEntityKeys,
                sample.secondaryTextReplaced,
                sample.generatedReply,
                sample.replyTemplateId,
                sample.replyVariables,
                sample.isFallbackTemplate,
                sample.fallbackReason,
                sample.replySafe,
                sample.replyCharCount,
                sample.replyAudioDurationMs,
                sample.complianceFlags,
                sample.finalNluScene,
                sample.finalNluIntent,
                sample.topicScene,
                sample.finalNluCallNature,
                sample.finalNluRiskLevel,
                sample.finalNluConfidence,
                sample.finalNluSceneMargin,
                sample.shouldClarify,
                sample.sceneCandidates,
                sample.riskReasons,
                sample.nluMatchedEvidence,
                sample.nluRejectedEvidence,
                json.encodeToString(sample.ruleDebugTrace?.sceneScores.orEmpty()),
                json.encodeToString(sample.ruleDebugTrace?.intentScores.orEmpty()),
                json.encodeToString(sample.ruleDebugTrace?.intentScores.orEmpty().flatMap { it.evidence }),
                sample.ruleDebugTrace?.finalSceneSource,
                json.encodeToString(sample.ruleDebugTrace?.risk?.matchedRiskIds.orEmpty()),
                json.encodeToString(sample.ruleDebugTrace?.risk?.rejectedRiskIds.orEmpty()),
                json.encodeToString(sample.ruleDebugTrace?.risk?.contextExemptedRiskIds.orEmpty()),
                sample.recognizedTextNormalized,
                sample.referenceTextRaw,
                sample.referenceTextNormalized,
                sample.cerEditDistance,
                sample.cerReferenceLength,
                sample.cer,
                sample.initialScene,
                sample.expectedScene,
                sample.actualScene,
                sample.sceneConfidenceState,
                sample.sceneMatched,
                sample.expectedIntent,
                sample.intentMatched,
                sample.expectedCallNature,
                sample.callNatureMatched,
                sample.expectedRiskLevel,
                sample.riskLevelMatched,
                json.encodeToString(sample.expectedDigitSpans),
                sample.expectedDeliveryIntent,
                sample.actualDeliveryIntent,
                sample.deliveryIntentMatched,
                sample.deliveryIntentScore,
                sample.deliveryIntentDecisionRule,
                sample.deliveryIntentMatchedEvidence,
                sample.deliveryIntentRejectedCandidates,
                sample.entityTp,
                sample.entityFp,
                sample.entityFn,
                sample.entityPrecision,
                sample.entityRecall,
                sample.entityF1,
                sample.strictEntitiesMatched,
                sample.requiredEntitiesIncluded,
                sample.locationMatched,
                sample.locationExactMatched,
                sample.locationCoreIncluded,
                sample.locationHierarchyMatched,
                sample.hotwordAccuracy,
                sample.outputMode,
                sample.responseLatencyMs,
                sample.turnTotalDurationMs,
                sample.peakProcessPssKb,
            ).joinToString(",") { value -> csvCell(value) }
        }
        return rows.joinToString("\n", postfix = "\n")
    }

    private fun csvCell(value: Any?): String {
        if (value == null) return ""
        if (value is Double && !value.isFinite()) return ""
        val text = value.toString().replace("\"", "\"\"")
        return "\"$text\""
    }

    @Serializable
    private data class WavCallFailures(
        val runId: String,
        val failures: List<WavCallSampleResult>,
    )
}
